
spring:
  application:
    name: brs-inventory-service
  zipkin:
    base-url: http://localhost:9411
    
  datasource:
    url: jdbc:mysql://localhost:3306/bus_reservation_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true      # Print SQL queries to console for debugging
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect

  activemq:
    broker-url: tcp://localhost:61616

eureka:
  client:
    service-url:
      defaultZone: http://brs-eureka-server:8070/eureka
      
server:
  port: 8082
  servlet:
    context-path: /inventory

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

