spring:
  application:
    name: brs-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka
server:
  port: 8072