
spring:
  application:
    name: brs-booking-service

  datasource:
    url: jdbc:mysql://localhost:3306/bus_reservation_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: none
      show-sql: true      # Print SQL queries to console for debugging
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  activemq:
    broker-url: tcp://localhost:61616
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka
server:
  port: 8083
  servlet:
    context-path: /booking