spring:
  application:
    name: brs-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      routes:
        - id: brs-auth-service
          uri: lb://BRS-AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: brs-booking-service
          uri: lb://BRS-BOOKING-SERVICE
          predicates:
            - Path=/booking/**
          filters:
            - AuthenticationFilter

        - id: brs-payment-service
          uri: lb://BRS-PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter

        - id: brs-inventory-service
          uri: lb://BRS-INVENTORY-SERVICE
          predicates:
            - Path=/inventory/**
          filters:
            - AuthenticationFilter

        - id: brs-admin-service
          uri: lb://BRS-ADMIN-SERVICE
          predicates:
            - Path=/admin/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka
server:
  port: 8072

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true